name: Blackbox Tests

on:
  push:
    branches:
      - main
    paths:
      - api/**
      - tests/blackbox/**
      - packages/**
      - package.json
      - pnpm-lock.yaml
      - .github/workflows/blackbox.yml
  workflow_call:

concurrency:
  group: blackbox-${{ github.ref }}
  cancel-in-progress: true

env:
  NODE_OPTIONS: --max_old_space_size=6144

jobs:
  common:
    name: common
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Prepare
        uses: ./.github/actions/prepare

      - name: Start services
        run:
          docker compose -f tests/blackbox/docker-compose.yml up auth-saml redis minio minio-mc -d --quiet-pull --wait

      - name: Run tests
        run: TEST_DB=sqlite3 pnpm run test:blackbox -- --project common

  db:
    name: ${{ matrix.vendor }}
    runs-on: ${{ matrix.vendor == 'mssql' && 'ubuntu-22.04' || 'ubuntu-latest' }}
    timeout-minutes: 60
    strategy:
      fail-fast: false
      matrix:
        vendor:
          - sqlite3
          - postgres
          - mysql
          - maria
          - mssql
          - oracle
          # - cockroachdb
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Prepare
        uses: ./.github/actions/prepare

      - name: Start mssql
        if: matrix.vendor == 'mssql'
        run: |
          curl https://packages.microsoft.com/keys/microsoft.asc | sudo tee /etc/apt/trusted.gpg.d/microsoft.asc
          sudo curl https://packages.microsoft.com/config/ubuntu/22.04/mssql-server-2022.list -o /etc/apt/sources.list.d/mssql-server.list
          sudo apt-get update
          sudo apt-get install -y mssql-server
          sudo /opt/mssql/bin/mssql-conf set network.tcpport 6105
          echo "en-US" | sudo tee /var/opt/mssql/language.txt > /dev/null
          sudo MSSQL_PID=Express ACCEPT_EULA=Y MSSQL_SA_PASSWORD='Test@123' /opt/mssql/bin/mssql-conf -n setup
          sudo systemctl restart mssql-server.service
          for i in {1..30}; do
              sqlcmd -S localhost,6105 -U SA -P 'Test@123' -Q "SELECT 1" && break
              sleep 2
          done
          sqlcmd -S localhost,6105 -U SA -P 'Test@123' -Q "ALTER DATABASE model SET COMPATIBILITY_LEVEL = 150" -l 30

      - name: Start database
        if: matrix.vendor != 'sqlite3' && matrix.vendor != 'mssql'
        run: docker compose -f tests/blackbox/docker-compose.yml up ${{ matrix.vendor }} -d --quiet-pull --wait

      - name: Start services
        run:
          docker compose -f tests/blackbox/docker-compose.yml up auth-saml redis minio minio-mc -d --quiet-pull --wait

      - name: Run tests
        run: TEST_DB=${{ matrix.vendor }} pnpm run test:blackbox -- --project db
