name: Changeset Check

on:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
      - edited
  issue_comment:
    types:
      - created
      - edited
      - deleted

permissions:
  contents: read
  pull-requests: read
  issues: read

jobs:
  changeset-check:
    runs-on: ubuntu-latest
    if: |
      github.event_name == 'pull_request' ||
      (github.event_name == 'issue_comment' && github.event.issue.pull_request)
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Validate Changeset Presence
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const prNumber = context.payload.pull_request?.number || context.payload.issue?.number;
            const query = `
              query($owner:String!,$repo:String!,$pr:Int!) {
                repository(owner:$owner,name:$repo) {
                  pullRequest(number:$pr) {
                    files(first:100) {
                      nodes {
                        path
                        changeType
                      }
                    }
                    comments(first:100) {
                      nodes {
                        author { login }
                        body
                        isMinimized
                      }
                    }
                  }
                }
              }
            `;
            const vars = {
              owner: context.repo.owner,
              repo: context.repo.repo,
              pr: prNumber
            };
            const result = await github.graphql(query, vars);

            const changesetFiles = result.repository.pullRequest.files.nodes.filter(file => 
              file.path.startsWith('.changeset/') && 
              file.path.endsWith('.md') &&
              (file.changeType === 'ADDED' || file.changeType === 'MODIFIED')
            );

            if (changesetFiles.length > 0) {
              core.info(`✅ Found changeset files in PR: ${changesetFiles.map(f => f.path).join(', ')}`);
              return;
            }

            const csComment = result.repository.pullRequest.comments.nodes.find(c =>
              c.author.login === 'changeset-bot'
            );

            if (!csComment) {
              core.info('✅ No changeset-bot comment found');
              return;
            }

            if (!csComment.body.includes('No Changeset found')) {
              core.info('✅ changeset-bot comment does not indicate missing changeset');
              return;
            }

            if (csComment.isMinimized) {
              core.info('✅ changeset-bot comment is hidden');
              return;
            }

            core.setFailed(`❌ Missing changeset - add changeset or hide changeset-bot comment`);
