name: Changeset Check

on:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
      - labeled
      - unlabeled

permissions:
  contents: read

jobs:
  changeset-check:
    name: Changeset Check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Check for Chore Label
        if: contains(github.event.pull_request.labels.*.name, 'Chore')
        run: |
          echo "✅ Chore label present"
          exit 0

      - name: Check for Changeset
        if: ${{ ! contains(github.event.pull_request.labels.*.name, 'Chore') }}
        run: |
          git fetch origin ${{ github.event.pull_request.base.ref }}
          git diff --name-only origin/${{ github.event.pull_request.base.ref }}...HEAD > changed.txt

          if grep -qE '^\.changeset/.*\.md$' changed.txt; then
            echo "✅ Found changeset file"
            exit 0
          fi

          echo "❌ Pull request must add a changeset or have the `Chore` label."
          exit 1
